# Run: uv run python 02-generative-ai-and-agents/05_code_interpreter.py
# Practice-question coverage: Q6, Q22, Q76, Q79, Q83.

"""Built-in Code Interpreter.

This example demonstrates:
- Invoking the Code Interpreter tool
- Inspecting the Python code generated by the model
- Viewing the execution results
- Returning the final answer

The Code Interpreter executes Python inside an isolated sandbox managed by
OpenAI. Treat generated code and outputs as untrusted until reviewed.
"""

from _shared.openai_client import openai_client
from _shared.config import settings


QUESTION = (
    "What is the compound interest on $10,000 at a 5% annual rate "
    "compounded annually for 10 years?"
)


def main() -> None:
    client = openai_client()

    print(f"Model: {settings().default_model}")
    print(f"Question: {QUESTION}\n")

    response = client.responses.create(
        model=settings().default_model,
        instructions=(
            "You are a data analyst. "
            "Always use Python for calculations to ensure accuracy."
        ),
        input=QUESTION,
        tools=[
            {
                "type": "code_interpreter",
                "container": {"type": "auto"},
            }
        ],
    )

    for item in response.output:

        if item.type == "code_interpreter_call":
            print("=== Code Interpreter ===\n")

            if getattr(item, "code", None):
                print("Python code generated:\n")
                print(item.code)

            if getattr(item, "outputs", None):
                print("\nExecution output:\n")

                for output in item.outputs:
                    output_type = getattr(output, "type", "")

                    if output_type == "logs":
                        print(output.logs)

                    elif output_type == "text":
                        print(output.text)

                    else:
                        print(output)

        elif item.type == "message":
            print("\n=== Final Answer ===\n")
            print(response.output_text)


if __name__ == "__main__":
    main()